# Generated by Django 4.2 on 2026-06-17 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sektor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(blank=True, max_length=20, null=True)),
                ('top_n', models.IntegerField(default=5)),
                ('judul', models.CharField(blank=True, max_length=255)),
                ('file_pdf', models.FileField(upload_to='pdf_results/', verbose_name='File PDF')),
                ('data_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sektor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riwayat_analisis', to='sektor.sektor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riwayat_analisis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Riwayat Analisis',
                'verbose_name_plural': 'Riwayat Analisis',
                'ordering': ['-created_at'],
            },
        ),
    ]
