# Generated by Django 4.2 on 2026-06-17 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('sifat', models.CharField(choices=[('BENEFIT', 'Benefit'), ('COST', 'Cost')], default='BENEFIT', max_length=10)),
                ('bobot', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kriteria',
                'verbose_name_plural': 'Daftar Kriteria',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='PairwiseComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuzzy_l', models.FloatField(verbose_name='Fuzzy l')),
                ('fuzzy_m', models.FloatField(verbose_name='Fuzzy m')),
                ('fuzzy_u', models.FloatField(verbose_name='Fuzzy u')),
                ('nilai_crisp', models.IntegerField(verbose_name='Nilai Crisp (1-9)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kriteria_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairwise_as_first', to='kriteria.kriteria')),
                ('kriteria_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairwise_as_second', to='kriteria.kriteria')),
            ],
            options={
                'verbose_name': 'Perbandingan Pairwise',
                'verbose_name_plural': 'Data Perbandingan Pairwise',
                'unique_together': {('kriteria_1', 'kriteria_2')},
            },
        ),
    ]
