# Generated by Django 4.2 on 2026-06-17 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sektor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_saham', models.CharField(max_length=10)),
                ('nama_perusahaan', models.CharField(max_length=200)),
                ('periode', models.CharField(max_length=20)),
                ('roe', models.FloatField(verbose_name='ROE (%)')),
                ('eps', models.FloatField(verbose_name='EPS (Rp)')),
                ('per', models.FloatField(verbose_name='PER (x)')),
                ('der', models.FloatField(verbose_name='DER (x)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sektor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saham_set', to='sektor.sektor')),
            ],
            options={
                'verbose_name': 'Saham',
                'verbose_name_plural': 'Daftar Saham',
                'ordering': ['kode_saham'],
                'unique_together': {('kode_saham', 'periode')},
            },
        ),
    ]
