# Generated by Django 4.2 on 2026-07-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saham', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saham',
            name='bi_rate',
            field=models.FloatField(blank=True, help_text='BI Rate (%)', null=True, verbose_name='BI Rate (%)'),
        ),
        migrations.AlterField(
            model_name='saham',
            name='nama_perusahaan',
            field=models.CharField(max_length=255),
        ),
    ]
